service: cart-service
frameworkVersion: '3'

useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1
  environment:
    PG_HOST: ${env:PG_HOST}
    PG_PORT: ${env:PG_PORT}
    PG_DATABASE: ${env:PG_DATABASE}
    PG_USER: ${env:PG_USER}
    PG_PASSWORD: ${env:PG_PASSWORD}
    GET_PRODUCT_LIST_LAMBDA_ARN: ${env:GET_PRODUCT_LIST_LAMBDA_ARN}
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 'lambda:InvokeFunction'
          Resource: '*'
        - Effect: Allow
          Action: 'lambda:InvokeAsync'
          Resource: '*'

custom:
  lambdasPath: dist/lambdas/index

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
  createUser:
    handler: ${self:custom.lambdasPath}.createUser
    events:
      - http:
          method: POST
          path: user
  getUser:
    handler: ${self:custom.lambdasPath}.getUser
    events:
      - http:
          method: GET
          path: user/{id}
  getOrder:
    handler: ${self:custom.lambdasPath}.getOrder
    events:
      - http:
          method: GET
          path: order/{id}
  createOrder:
    handler: ${self:custom.lambdasPath}.createOrder
    events:
      - http:
          method: POST
          path: order
  updateOrder:
    handler: ${self:custom.lambdasPath}.updateOrder
    events:
      - http:
          method: PATCH
          path: order/{id}
  findUserCart:
    handler: ${self:custom.lambdasPath}.findUserCart
    events:
      - http:
          method: GET
          path: cart/{userId}
  clearUserCart:
    handler: ${self:custom.lambdasPath}.clearUserCart
    events:
      - http:
          method: DELETE
          path: cart/{userId}
  updateUserCart:
    handler: ${self:custom.lambdasPath}.updateUserCart
    events:
      - http:
          method: PUT
          path: cart/{userId}
  checkout:
    handler: ${self:custom.lambdasPath}.checkout
    events:
      - http:
          method: POST
          path: cart/checkout/{userId}